export * from './interfaces.ts';
export * from './bonification.interface.ts';
export * from './suspension-type.interface.ts';
export * from './other-income.interface.ts';
export * from './employee-by-position.interface.ts';
export * from './deduction-type.interface.ts';
export * from './benefit-type.interface.ts';
export * from './extra-hour.interface.ts';
export * from './suspension.interface.ts';
export * from './absence.interface.ts';
export * from './absenceTypes.interface.ts'
export * from './suspensionTypes.interface.ts'
export * from './deductionTypes.interface.ts'